services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    container_name: yourmusic-backend-dev
    restart: no
    ports:
      - '${PORT}:${PORT}'
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - GOOGLE_SCOPE=${GOOGLE_SCOPE}
      - YOUTUBE_BASE_URL=${YOUTUBE_BASE_URL}
      - YOUTUBE_API_LIMIT_PER_SECOND=${YOUTUBE_API_LIMIT_PER_SECOND}
      - YOUTUBE_API_LIMIT_PER_MINUTE=${YOUTUBE_API_LIMIT_PER_MINUTE}
      - YOUTUBE_API_LIMIT_QUEUE_SIZE=${YOUTUBE_API_LIMIT_QUEUE_SIZE}
      - YOUTUBE_BATCH_SIZE=${YOUTUBE_BATCH_SIZE}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SPOTIFY_REDIRECT_URI=${SPOTIFY_REDIRECT_URI}
      - SPOTIFY_API_ENDPOINT=${SPOTIFY_API_ENDPOINT}
      - SPOTIFY_ADD_SONG_BATCH_SIZE=${SPOTIFY_ADD_SONG_BATCH_SIZE}
      - SPOTIFY_API_LIMIT_PER_SECOND=${SPOTIFY_API_LIMIT_PER_SECOND}
      - SPOTIFY_API_LIMIT_PER_MINUTE=${SPOTIFY_API_LIMIT_PER_MINUTE}
      - SPOTIFY_API_LIMIT_QUEUE_SIZE=${SPOTIFY_API_LIMIT_QUEUE_SIZE}
      - MAX_WORKERS=${MAX_WORKERS}
      - MAX_BROWSERS_PER_WORKER=${MAX_BROWSERS_PER_WORKER}
      - MAX_CONCURRENT_PAGES=${MAX_CONCURRENT_PAGES}
      - WORKER_TIMEOUT=${WORKER_TIMEOUT}
    volumes:
      - .:/app
      - /app/node_modules
      - ./.cache:/app/.cache
    command: npm run start:dev
    working_dir: /app
    depends_on:
      - db
    networks:
      - db-network
      - public-network
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  db:
    image: mysql:8.0
    container_name: yourmusic-db-dev
    restart: no
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - yourmusic-db-data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - db-network
    expose:
      - '3306'
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

networks:
  db-network:
    driver: bridge
    internal: true
  public-network:
    driver: bridge

volumes:
  yourmusic-db-data:
